source 'https://rubygems.org'

group :lint do
  gem 'mdl', '>= 0.7.0'
end

group :integration do
  gem 'test-kitchen'
  gem 'berkshelf', '>= 8.1.4'
  gem 'rake', '>= 12.3.3'
end

group :vagrant do
  gem 'kitchen-vagrant', '>= 2.0.2'
end

group :docker do
  gem 'kitchen-docker'
end
