source 'https://rubygems.org'

group :lint do
  gem 'mdl'
end

group :integration do
  gem 'test-kitchen'
  gem 'berkshelf', '>= 7.0.10'
  gem 'rake', '>= 12.3.3'
end

group :vagrant do
  gem 'kitchen-vagrant'
end

group :docker do
  gem 'kitchen-docker'
end
