def run(command)
    raise "Failed to execute '#{command}'" if !system(command)
end

task :default =>  [:gates]

desc 'gates'
task :gates do
    Dir.chdir('test') do
        output = `kitchen test`
        return $?.to_i
    end
end

desc 'lint'
task :lint do
    run('sh test/verify.sh')
end

desc 'integration test'
task :integration do
    Dir.chdir('test') do
        run('kitchen test')
    end
end
