task :default =>  [:gates]

desc 'gates'
task :gates do
    Rake::Task['lint'].invoke
    Rake::Task['test:integration'].invoke
end

desc 'lint'
task :lint do
    sh 'sh test/verify.sh'
end

namespace 'test' do
    desc 'integration tests'
    task :integration do
        Dir.chdir('test') do
            sh 'kitchen test'
        end
    end
end
