language: ruby
services: docker

sudo: true
cache: bundler
rvm: 2.2

install:
  - sudo apt-get install shellcheck
  - travis_wait bundle install --gemfile=test/Gemfile --without vagrant

script:
  - bash test/verify.sh
  - KITCHEN_LOCAL_YAML="./.kitchen.docker.yml" rake --rakefile=test/Rakefile test:integration
