services: docker

sudo: true
cache:
  directories:
    - $HOME/test/vendor/bundle

install:
  - bundle install --gemfile=test/Gemfile --without vagrant

script: KITCHEN_LOCAL_YAML="./.kitchen.docker.yml" rake --rakefile=test/Rakefile
