services: docker

addons:
  apt:
    sources:
      - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
      - shellcheck

sudo: true
cache:
  directories:
    - $HOME/test/vendor/bundle

install:
  - bundle install --gemfile=test/Gemfile --without vagrant

script: KITCHEN_LOCAL_YAML="./.kitchen.docker.yml" rake --rakefile=test/Rakefile
