#update homebrew
update

#upgrade already installed homebrew packages
upgrade --all

#install my standard packages
tap homebrew/versions
tap homebrew/dupes
tap josegonzalez/homebrew-php
install php55
install php55-xdebug
install php55-ssh2
install composer
install python

install ant
install augeas
install libxml2
install libyaml
install mercurial
install git
install tig
install node
install nvm
install heroku-toolbelt

install wget
install jq
install nmap
install mtr
install minicom
install openssl
install ssh-copy-id
install keybase
install pkg-config
install readline
install ruby
link --force ruby
install rbenv
install vim
install maven
install corkscrew
install thefuck
install dos2unix
install shellcheck
install docker

tap nviennot/tmate
install tmate
install tmux

install bash-completion
install grc
install source-highlight

install highlight

# Remove outdated versions from the cellar
cleanup
