tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'

brew 'gpg-agent'
brew 'gnupg2'
brew 'keybase'
brew 'lastpass-cli', args: ['with-pinentry', 'with-doc']

brew 'bash'
brew 'bash-completion'
brew 'coreutils'
brew 'readline'
brew 'dos2unix'
brew 'jq'
brew 'thefuck'
brew 'tmate'
brew 'tmux'

brew 'grc'
brew 'source-highlight'
brew 'jp2a'

brew 'wget'
brew 'nmap'
brew 'mtr'
brew 'minicom'
brew 'openssl'
brew 'ssh-copy-id'
brew 'corkscrew'
cask 'pl2303'

brew 'mas'
brew 'git'
brew 'hub'
brew 'tig'
cask 'p4merge'
brew 'mercurial'
brew 'heroku-toolbelt'

brew 'nvm'
cask 'java'
brew 'maven'
brew 'rbenv'
brew 'ruby-build'
brew 'rbenv-bundler'
brew 'rbenv-default-gems'
brew 'python'
brew 'perl'

cask 'chefdk'

brew 'vim'
cask 'atom'
cask 'macdown'
cask 'webstorm'
cask 'google-cloud-sdk'
cask 'dash'
brew 'shellcheck'

cask 'ccmenu'

cask 'google-chrome'
cask 'brave'
cask 'firefox'
cask 'adobe-reader'
cask 'dropbox'
cask 'vlc'
cask 'evernote'
cask 'transmission'
cask 'postman'

cask 'aerial'
cask 'caffeine'

cask 'slack'
cask 'discord'

mas 'LastPass', id: 926036361
